$(dwm_include Makefile.vars)
all::
	${MAKE} -C man
	${MAKE} -C latex

tarprep::
	${MAKE} -C man $@
	${MAKE} -C latex $@

tarprep-clean::
	${MAKE{ -C man $@
	${MAKE{ -C latex $@

clean::
	${MAKE} -C man $@
	${MAKE} -C latex $@

distclean::
	${MAKE} -C man $@
	${MAKE} -C latex $@

